# Generated by Django 6.1 on 2026-08-20 09:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashDrawerShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.DateTimeField(auto_now_add=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Opening Float (PKR)')),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Counted Closing Cash (PKR)')),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_wallet_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=15)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Shift Notes / Discrepancy Reason')),
                ('is_synced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cash Drawer Shift',
                'verbose_name_plural': 'Cash Drawer Shifts',
                'ordering': ['-opening_time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Customer Name')),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Delivery / Postal Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Customer Notes / Preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Table Name / Number')),
                ('floor_section', models.CharField(default='Main Hall', max_length=100, verbose_name='Floor / Section')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Seating Capacity')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=20, verbose_name='Current Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Location Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dining Table',
                'verbose_name_plural': 'Dining Tables',
                'ordering': ['floor_section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Invoice Number')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('held', 'Held / Parked'), ('refunded', 'Refunded / Returned'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20)),
                ('order_type', models.CharField(choices=[('walk_in', 'Walk-in'), ('dine_in', 'Dine-in'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='walk_in', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal (PKR)')),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed Amount (PKR)'), ('percentage', 'Percentage (%)')], default='none', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount (PKR)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax Rate (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax (PKR)')),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Service Charge (%)')),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Service Charges (PKR)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Net Amount (PKR)')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], default='cash', max_length=20)),
                ('amount_tendered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cash Received (PKR)')),
                ('change_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Change Returned (PKR)')),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coupon / Promo Code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Order / Billing Notes')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='Refund Reason')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Refund Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sale Invoice',
                'verbose_name_plural': 'Sales Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name Snapshot')),
                ('variant_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size Name Snapshot')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Selling Price (PKR)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cost Price (PKR)')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Line Discount')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Line Total (PKR)')),
                ('is_refunded', models.BooleanField(default=False)),
                ('refunded_quantity', models.IntegerField(default=0)),
                ('is_synced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sale Line Item',
                'verbose_name_plural': 'Sale Line Items',
            },
        ),
    ]
