# Generated by Django 6.1 on 2026-08-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Table Name / Number')),
                ('floor_section', models.CharField(default='Main Hall', max_length=100, verbose_name='Floor / Section')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Seating Capacity')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=20, verbose_name='Current Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Location Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dining Table',
                'verbose_name_plural': 'Dining Tables',
                'ordering': ['floor_section', 'name'],
            },
        ),
    ]
