# Generated by Django 6.1 on 2026-08-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('dine_in', 'Dine-in'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], db_index=True, default='walk_in', max_length=20),
        ),
    ]
