# Generated by Django 6.1 on 2026-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_diningtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrawershift',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
