# Generated by Django 6.1 on 2026-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
