# Generated by Django 6.1 on 2026-08-15 07:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Barcode / SKU')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cost Price (PKR)')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Selling Price (PKR)')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Current Stock')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='Low Stock Alert Threshold')),
                ('unit', models.CharField(choices=[('Pcs', 'Pieces (Pcs)'), ('Kg', 'Kilogram (Kg)'), ('Gram', 'Gram (g)'), ('Liter', 'Liter (L)'), ('Pack', 'Pack'), ('Box', 'Box'), ('Dozen', 'Dozen')], default='Pcs', max_length=20, verbose_name='Unit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
