# Generated by Django 6.1 on 2026-09-05 09:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('icon', models.CharField(blank=True, default='📦', max_length=20, verbose_name='Category Emoji / Icon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_synced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('has_variants', models.BooleanField(default=False, verbose_name='Has Sizes / Variations (e.g. Small, Medium, Large)')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Selling Price (PKR)')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cost Price (PKR)')),
                ('stock_quantity', models.IntegerField(blank=True, default=0, verbose_name='Stock Quantity')),
                ('track_stock', models.BooleanField(default=True, verbose_name='Track Stock Quantity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active for Sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Size / Variation Name (e.g. Small, Medium, Large)')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cost Price (PKR)')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Selling Price (PKR)')),
                ('stock_quantity', models.IntegerField(blank=True, default=0, verbose_name='Stock Quantity')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_synced', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Size / Variant',
                'verbose_name_plural': 'Product Sizes / Variants',
                'ordering': ['selling_price'],
            },
        ),
    ]
