# Generated by Django 6.1 on 2026-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='📦', max_length=20, verbose_name='Category Emoji / Icon'),
        ),
    ]
