# Generated by Django 6.1 on 2026-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
