# Generated by Django 6.1 on 2026-09-02 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_date'),
        ('sales', '0004_sale_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='sales.cashdrawershift'),
        ),
    ]
