# Generated by Django 6.1 on 2026-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('text_content', models.TextField()),
                ('html_content', models.TextField(blank=True, null=True)),
                ('to_emails', models.TextField(help_text='JSON encoded list of emails')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('sent', 'Sent')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_popup_active', models.BooleanField(default=False, help_text='Enable or disable the recurring popup modal')),
                ('is_navbar_active', models.BooleanField(default=False, help_text='Enable or disable the top navbar badge')),
                ('interval_minutes', models.IntegerField(default=15, help_text='Popup re-occurrence interval in minutes after dismissal')),
                ('pending_month', models.CharField(blank=True, default='Current Month', help_text='Month or period for which payment is due', max_length=100)),
                ('pending_amount', models.CharField(blank=True, default='0', help_text='Amount due (e.g. Rs. 15,000)', max_length=100)),
                ('account_info', models.TextField(blank=True, default='', help_text='Bank details, Account Title, Account No, Raast ID, IBAN')),
                ('alert_title', models.CharField(blank=True, default='Software Subscription Payment Due', max_length=200)),
                ('alert_message', models.TextField(blank=True, default='Your monthly POS software maintenance/subscription fee is pending. Please transfer the payment to keep all system services running without disruption.')),
                ('due_date', models.CharField(blank=True, default='', help_text='Due date (e.g. 25-Aug-2026 or Immediate)', max_length=100)),
                ('contact_info', models.CharField(blank=True, default='', help_text='Support helpline / WhatsApp', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Alert',
                'verbose_name_plural': 'Payment Alerts',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='PakPOS', max_length=100)),
                ('app_subtitle', models.CharField(default='Professional Point of Sale', max_length=200)),
                ('app_currency', models.CharField(default='PKR', max_length=20)),
                ('app_footer_text', models.CharField(default='Powered by PakPOS', max_length=200)),
                ('app_primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('pos_operation_mode', models.CharField(choices=[('retail', 'Retail'), ('restaurant', 'Restaurant')], default='restaurant', max_length=50)),
                ('time_zone', models.CharField(default='Asia/Karachi', max_length=100)),
                ('pos_default_tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pos_default_service_charge_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pos_default_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pos_auto_apply_discount', models.BooleanField(default=False)),
                ('pos_default_delivery_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pos_shift_start_hour', models.IntegerField(default=0)),
                ('pos_shift_end_hour', models.IntegerField(default=23)),
                ('products_per_page', models.IntegerField(default=50)),
                ('session_cookie_age_days', models.IntegerField(default=30)),
                ('owner_email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_email_3', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_enabled', models.BooleanField(default=True, help_text='Global switch to enable/disable background email sending')),
                ('gdrive_backup_enabled', models.BooleanField(default=True, help_text='Enable/disable Google Drive cloud backup')),
                ('gdrive_remote_active', models.BooleanField(default=True, help_text="Controlled via Google Sheets Actions tab 'backup_active'")),
                ('gdrive_webhook_url', models.CharField(blank=True, help_text='Google Apps Script Webhook URL', max_length=500, null=True)),
                ('gdrive_folder_id_or_link', models.CharField(blank=True, help_text='Google Drive Folder Link or Folder ID', max_length=500, null=True)),
                ('gdrive_backup_time', models.CharField(default='23:00', help_text='Daily backup schedule time (HH:MM in 24-hour format)', max_length=10)),
                ('gdrive_max_files', models.IntegerField(default=3, help_text='Number of latest backup files to retain on Google Drive')),
                ('gdrive_last_upload_time', models.DateTimeField(blank=True, null=True)),
                ('gdrive_last_upload_status', models.CharField(blank=True, max_length=255, null=True)),
                ('gdrive_last_file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
