# Generated by Django 6.1 on 2026-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('text_content', models.TextField()),
                ('html_content', models.TextField(blank=True, null=True)),
                ('to_emails', models.TextField(help_text='JSON encoded list of emails')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('sent', 'Sent')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='PakPOS', max_length=100)),
                ('app_subtitle', models.CharField(default='Professional Point of Sale', max_length=200)),
                ('app_currency', models.CharField(default='PKR', max_length=20)),
                ('app_footer_text', models.CharField(default='Powered by PakPOS', max_length=200)),
                ('app_primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('pos_operation_mode', models.CharField(choices=[('retail', 'Retail'), ('restaurant', 'Restaurant')], default='restaurant', max_length=50)),
                ('time_zone', models.CharField(default='Asia/Karachi', max_length=100)),
                ('pos_default_tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pos_default_service_charge_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pos_default_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pos_auto_apply_discount', models.BooleanField(default=False)),
                ('pos_default_delivery_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pos_shift_start_hour', models.IntegerField(default=0)),
                ('pos_shift_end_hour', models.IntegerField(default=23)),
                ('products_per_page', models.IntegerField(default=50)),
                ('session_cookie_age_days', models.IntegerField(default=30)),
                ('owner_email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_email_3', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
