# Generated by Django 6.1 on 2026-08-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Enable or disable the payment reminder popup and navbar banner')),
                ('interval_minutes', models.IntegerField(default=15, help_text='Popup re-occurrence interval in minutes after dismissal')),
                ('pending_month', models.CharField(blank=True, default='Current Month', help_text='Month or period for which payment is due', max_length=100)),
                ('pending_amount', models.CharField(blank=True, default='0', help_text='Amount due (e.g. Rs. 15,000)', max_length=100)),
                ('account_info', models.TextField(blank=True, default='', help_text='Bank details, Account Title, Account No, Raast ID, IBAN')),
                ('alert_title', models.CharField(blank=True, default='Software Subscription Payment Due', max_length=200)),
                ('alert_message', models.TextField(blank=True, default='Your monthly POS software maintenance/subscription fee is pending. Please transfer the payment to keep all system services running without disruption.')),
                ('due_date', models.CharField(blank=True, default='', help_text='Due date (e.g. 25-Aug-2026 or Immediate)', max_length=100)),
                ('contact_info', models.CharField(blank=True, default='', help_text='Support helpline / WhatsApp', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Alert',
                'verbose_name_plural': 'Payment Alerts',
            },
        ),
    ]
