# Generated by Django 6.1 on 2026-08-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paymentalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentalert',
            name='is_active',
        ),
        migrations.AddField(
            model_name='paymentalert',
            name='is_navbar_active',
            field=models.BooleanField(default=False, help_text='Enable or disable the top navbar badge'),
        ),
        migrations.AddField(
            model_name='paymentalert',
            name='is_popup_active',
            field=models.BooleanField(default=False, help_text='Enable or disable the recurring popup modal'),
        ),
    ]
