# Generated by Django 6.1 on 2026-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_paymentalert_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='email_enabled',
            field=models.BooleanField(default=True, help_text='Global switch to enable/disable background email sending'),
        ),
    ]
