# Generated by Django 6.1 on 2026-08-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsetting_email_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='gdrive_backup_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable Google Drive cloud backup'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='gdrive_backup_time',
            field=models.CharField(default='23:00', help_text='Daily backup schedule time (HH:MM in 24-hour format)', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='gdrive_folder_id_or_link',
            field=models.CharField(blank=True, help_text='Google Drive Folder Link or Folder ID', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='gdrive_last_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='gdrive_last_upload_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='gdrive_last_upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='gdrive_max_files',
            field=models.IntegerField(default=3, help_text='Number of latest backup files to retain on Google Drive'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='gdrive_remote_active',
            field=models.BooleanField(default=True, help_text="Controlled via Google Sheets Actions tab 'backup_active'"),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='gdrive_webhook_url',
            field=models.CharField(blank=True, help_text='Google Apps Script Webhook URL', max_length=500, null=True),
        ),
    ]
